### ISSUE TITLE
Feature request: remove grade from sensor name

### ISSUE THREAD

**Issue by scaarup** [JBoye/HA-Aula#10]
My kids bumped up a grade in school now, and sensors changed names from eg. 
sensor.3a_emilie
to
sensor.4a_emilie

Which means, that I have to go through automations and dashboards to make corrections. Could we change the sensor name to not contain the class grade? Like sensor.aula_emilie?
Thanks.

**Comment by JBoye** [comment]
Jeg kan godt se din pointe, men jeg tror det kan give problemer når et barn er registreret i flere institutioner feks 4A og SFO

**Comment by scaarup** [comment]
Min datter går i 4A og SFO, men er kun registreret som en enkelt entity - "sensor.4a_emilie". Har du multiple entities per barn?

**Comment by JBoye** [comment]
Jeg har ikke, da min datter kun går i vuggestue, men jeg har set andre der har flere.

Optimalt set skulle der laves et opsætningsflow når man opretter integrationen hvor man selv kunne bestemme

**Comment by scaarup** [comment]
Ja det ville måske være optimalt.

Hvis jeg retter linje 49 i sensor.py til
`group_name = self._client._daily_overview[str(self._child["id"])]["institutionProfile"]["institutionName"]`

Så får jeg nogle fine sensor names:
sensor.hojelse_skole_emilie
sensor.hojelse_skole_rasmus

Jeg tænker logikken må være, at hvis man har samme barn flere gange i Aula, så må det være fordi barnet er tilknyttet multiple institutioner.
