### ISSUE TITLE
Sensor pludselig forsvundet

### ISSUE THREAD

**Issue by ghozt1989** [JBoye/HA-Aula#14]
Hej jeg har pludselig mistet min sensor.

Har disse 2 fejl i loggen
https://pastebin.com/SVKaCJmF
https://pastebin.com/NR9h9gbg

**Comment by Optimerius** [comment]
Jeg oplevede noget tilsvarende i sidste uge. Det viste sig at være min Unilogin kode som skulle ændres, da den gamle pludselig var udløbet. Det betød at der kom en besked op på siden ved login på Aula via Unilogin, hvor scriptet så ikke kunne finde de ting den forsøgte.
Da jeg skiftede min kode, som jeg blev bedt om ved login med Unilogin, så virkede det igen.

**Comment by ghozt1989** [comment]
> Jeg oplevede noget tilsvarende i sidste uge. Det viste sig at være min Unilogin kode som skulle ændres, da den gamle pludselig var udløbet. Det betød at der kom en besked op på siden ved login på Aula via Unilogin, hvor scriptet så ikke kunne finde de ting den forsøgte. Da jeg skiftede min kode, som jeg blev bedt om ved login med Unilogin, så virkede det igen.

Tusind tak for det. Det virker igen nu :D mega fedt du har redet husfreden 👍  :)
