### ISSUE TITLE
Feature request: Tilføj skoleskema som calendar entities

### ISSUE THREAD

**Issue by scaarup** [JBoye/HA-Aula#16]
Tilføj skoleskema som calendar entities. Der er en kalender i Aula:

'https://www.aula.dk/api/v14/?method=calendar.getEventsByProfileIdsAndResourceIds'

Der skal spørges på på childids og en tidsperiode. Eksempel post data:
'{"instProfileIds":[1356736,1378381],"resourceIds":[],"start":"2022-10-10 00:00:00.0000+02:00","end":"2022-10-15 00:00:00.0000+02:00"}'

**Comment by JBoye** [comment]
God ide, jeg kigger på det om 4 års tid når min datter starter i folkeskolen ;-)

**Comment by Jogge** [comment]
@scaarup Jeg ser du har lavet et nyt projekt her: https://github.com/scaarup/aula

Er det fordi dette repo har været for inaktivt og sløv til at acceptere PR? 🙂

**Comment by scaarup** [comment]
> @scaarup Jeg ser du har lavet et nyt projekt her: https://github.com/scaarup/aula
> 
> Er det fordi dette repo har været for inaktivt og sløv til at acceptere PR? 🙂

Ja lidt :). Jeg havde "tusind" idéer og selv de mindste af dem, kneb det med at få igennem her. Så tænkte det var meget nemmere og hurtigere at starte lidt på en frisk ;)

**Comment by scaarup** [comment]
Det må du meget gerne 🙂. Jeg er den eneste, der har testet det indtil videre og kunne godt bruge lidt feedback.
