### ISSUE TITLE
Forældre vs. medarbejder

### ISSUE THREAD

**Issue by WonderMoose** [JBoye/HA-Aula#4]
Jeg har forsøgt at få din component til at virke med mit Unilogin, men desværre uden held. 
Jeg tror problemet ligger i, at jeg skal vælge mellem at være Forældre/kontaktperson eller medarbejder, som jeg ikke umiddelbart kan se bliver håndteret i din kode (ret mig gerne hvis jeg tager fejl. Er ikke udvikler, men læser lidt kode engang imellem). 

Umiddelbart ligner det, at Morten Helmstedt som du har søgt inspiration hos, har postet noget omkring det [her](https://helmstedt.dk/2021/05/aulas-api-en-opdatering/?fbclid=IwAR2-y-7sUMyD-PosPqGUiPwBlBlr17I4twBjkzIS1iA28aMHKrs4sjDoK2E)

Som nævnt, er jeg ikke ret erfaring indenfor faget, men har da prøvet at se, om jeg kunne rette lidt til, dog uden held. 

Er det noget som du i forvejen har hørt om og måske har en idé om, hvordan den kan løses?

**Comment by JBoye** [comment]
Godt spørgsmål. 

Det bliver i hvert fald svært for mig at løse, da jeg ikke selv har medarbejder login.

Hvis andre har lyst og evner til at kigge på det må de meget gerne

**Comment by jannsvej** [comment]
Hej Jonas
Super arbejde, det virker perfekt :) Jeg har indtil nu brugt min bedre halvdels login, da mit eget bliver spurgt til rolle. Jeg har løst det ved at rette linje 24 i client.py til
`user_data = { 'username': self._username, 'password': self._password, 'selected-aktoer': "KONTAKT" }`

**Comment by WonderMoose** [comment]
Perfekt! Så var jeg alligevel lidt på rette vej. Jeg fik nok bare gjort det hele meget mere kompliceret end det egentlig var. 
Tak for hjælpen
