### ISSUE TITLE
Unilogin forsvinder til august 2022

### ISSUE THREAD

**Issue by Optimerius** [JBoye/HA-Aula#9]
Vi er netop blevet orienteret fra skolen om, at unilogin forsvinder fra august. Login skal fremover foregå udelukkende via NemID/MitID for forældre.
Det tegner ikke godt for muligheden for at trække data ud af Aula :(

**Comment by Jogge** [comment]
Mon ikke der bliver givet en eller anden form for token ved login i Aula, som man kan bruge i stedet, og som ikke bare udløber. Jeg tænker specielt på at man i Aula på iOS eller Android ikke skal logge ind med NemID/MitID hver gang. Jeg har da været logget ind i et år uden at skulle logge ind igen med NemID eller MitID.

**Comment by JBoye** [comment]
Hvilken kommune/skole?

Jeg har ikke hørt noget om det her i Aarhus

**Comment by Uberpainer** [comment]
Vi har heller ikke hørt noget i Aalborg kommune om at Unilogin skulle forsvinde. dog opfordres forældre til at benytte sig af NemID/MitID fremfor Unilogin.

**Comment by LordHolt** [comment]
Hej - Kan det passe at UniLogin er lukket? 
Se vedhæftet:
https://viden.stil.dk/display/STILVIDENOFFENTLIG/Siden+%27mit.uni-login.dk%27+lukker+mandag+den+17.+oktober

Kan man på anden måde logge ind?
